"""account type table

Revision ID: 22de388ecb44
Revises: eedda08314d1
Create Date: 2019-11-08 00:38:34.048728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22de388ecb44'
down_revision = 'eedda08314d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_type'))
    )
    op.add_column('account', sa.Column('type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_account_type_id_account_type'), 'account', 'account_type', ['type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_account_type_id_account_type'), 'account', type_='foreignkey')
    op.drop_column('account', 'type_id')
    op.drop_table('account_type')
    # ### end Alembic commands ###
