"""account type check constraint

Revision ID: 2d5cd453cbc3
Revises: 22de388ecb44
Create Date: 2019-11-09 18:00:11.473117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d5cd453cbc3'
down_revision = '22de388ecb44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_account_type_id_account_type', 'account', type_='foreignkey')
    op.drop_column('account', 'type_id')
    op.drop_table('account_type')
    op.add_column('account', sa.Column('type', sa.String(length=9), nullable=False))
    op.create_check_constraint('types', 'account', "type IN ('Asset', 'Liability', 'Equity', 'Income', 'Expense')")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('types', 'account', type_ = 'check')
    op.drop_column('account', 'type')
    op.create_table('account_type',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('type', mysql.VARCHAR(collation='utf8_bin', length=25), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.add_column('account', sa.Column('type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_account_type_id_account_type', 'account', 'account_type', ['type_id'], ['id'])
    # ### end Alembic commands ###