"""add budget table

Revision ID: 6f6dbdb6c90e
Revises: dd561ed01cf4
Create Date: 2019-11-13 00:30:56.911709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f6dbdb6c90e'
down_revision = 'dd561ed01cf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_budget_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget'))
    )
    op.add_column('account', sa.Column('budget_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_account_budget_id_budget'), 'account', 'budget', ['budget_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_account_budget_id_budget'), 'account', type_='foreignkey')
    op.drop_column('account', 'budget_id')
    op.drop_table('budget')
    # ### end Alembic commands ###
