"""user last budget

Revision ID: 8ca5cbae5e1d
Revises: c486dedee2c3
Create Date: 2019-11-13 01:59:12.359631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ca5cbae5e1d'
down_revision = 'c486dedee2c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_budget_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_user_last_budget_id_budget'), 'user', 'budget', ['last_budget_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_last_budget_id_budget'), 'user', type_='foreignkey')
    op.drop_column('user', 'last_budget_id')
    # ### end Alembic commands ###
