"""remove user-account relationship

Revision ID: c486dedee2c3
Revises: 6f6dbdb6c90e
Create Date: 2019-11-13 00:45:12.763440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c486dedee2c3'
down_revision = '6f6dbdb6c90e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_account_holder_id_user', 'account', type_='foreignkey')
    op.drop_column('account', 'holder_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('holder_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_account_holder_id_user', 'account', 'user', ['holder_id'], ['id'])
    # ### end Alembic commands ###
