"""asset type table

Revision ID: dd561ed01cf4
Revises: 567b24df7edb
Create Date: 2019-11-10 02:39:39.394798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd561ed01cf4'
down_revision = '567b24df7edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_type'))
    )
    op.add_column('posting', sa.Column('asset_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_posting_asset_type_id_asset_type'), 'posting', 'asset_type', ['asset_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_posting_asset_type_id_asset_type'), 'posting', type_='foreignkey')
    op.drop_column('posting', 'asset_type_id')
    op.drop_table('asset_type')
    # ### end Alembic commands ###
