"""journal new fields

Revision ID: eedda08314d1
Revises: bf8b217249dc
Create Date: 2019-11-07 23:31:58.826394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eedda08314d1'
down_revision = 'bf8b217249dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('journal', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('journal', sa.Column('payee', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal', 'payee')
    op.drop_column('journal', 'description')
    op.drop_column('journal', 'date')
    # ### end Alembic commands ###
